# Generated by Django 4.2.2 on 2023-09-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_choice_votes_vote_vote_unique_user_choice"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_user_choice",
        ),
    ]
